/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameUI from "./script/GameUI"
import GameControl from "./script/GameControl"
import Bullet from "./script/Bullet"
import DropBox from "./script/DropBox"
import resource from "./script/resource"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/GameUI.js",GameUI);
		reg("script/GameControl.js",GameControl);
		reg("script/Bullet.js",Bullet);
		reg("script/DropBox.js",DropBox);
    }
}
GameConfig.width = 750;
GameConfig.height = 1144;
GameConfig.bgColor = "#5a7b9a";
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "test/TestScene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = true;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
Laya.loader.load(resource, Laya.Handler.create(this, function (e) {
    let resManager = ResLoader.getInstance();
    let loading = new ui.view.gameLoadingUI();
    Laya.stage.addChild(loading);
    let sp_mask = loading.sp_mask;
    sp_mask.optimizeScrollRect = true;
    const progressTip = document.getElementById('progress_tip');
    const progress = document.getElementById('progress');
    const percent = document.getElementById('percent');
    const num = +pre;
    percent.innerHTML = `${num}%`;
    progress.style.width = `${num}%`;
    const body = document.body;
    body.className = body.className.replace('no-scroll', '');
    body.removeChild(progress.parentNode);
    body.removeChild(progressTip);
    if (GLOBAL.DATA.STATUS === 4) {
        const finishLayer = new FinishLayer();
        Tiny.app.run(finishLayer);
    } else {
        const menuLayer = new MenuLayer();
        Tiny.app.run(menuLayer);
        // menuLayer.emit('transitionend');
    }
    Tiny.app.view.style.opacity = '1';
    window.kfcMario.runDanmu && window.kfcMario.runDanmu();
    window.kfcMario.gameInitCallback && window.kfcMario.gameInitCallback();
}));
