/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameUI from "./script/GameUI"
import GameControl from "./script/GameControl"
import Bullet from "./script/Bullet"
import DropBox from "./script/DropBox"
import Girl from "./script/Girl"
import MainLayer from "./script/MainLayer"
import MenuLayer from "./script/menuLayer"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/GameUI.js",GameUI);
		reg("script/GameControl.js",GameControl);
		reg("script/Bullet.js",Bullet);
        reg("script/DropBox.js",DropBox);
        reg("script/Girl.js",Girl);
        reg("script/MainLayer.js",MainLayer);
        reg("script/menuLayer.js",MenuLayer);
    }
}
GameConfig.width = 750;
GameConfig.height = 1144;
GameConfig.bgColor = "#5a7b9a";
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "test/TestScene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = true;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
